"use client"
import { createContext, useState, useEffect } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navigation from './components/Navigation';
import Footer from './components/Footer';
import './globals.css'

export const UserContext = createContext(null);

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };



// {"id":2,"email":"sam@gmail.com","tokens":{"refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwOTEzMjAyMSwiaWF0IjoxNzA4NTI3MjIxLCJqdGkiOiIwNmNhYzYwNjMzZWY0ZDhiOGY3MGI4NWI3ZTJkZGEzYiIsInVzZXJfaWQiOjJ9.2y8KZgQaF6O21q13nsx2Js9x1XMtC-qOMvzFZAhccZM","access":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4NjEzNjIxLCJpYXQiOjE3MDg1MjcyMjEsImp0aSI6ImE1N2YxOTg0YTBjNjQwYzViNjQyZGQ4ZTg0MmJlNmJmIiwidXNlcl9pZCI6Mn0._1BqPjvcdC6KaOzsXyWYplqceyaxngixZbmKd4K9diI"},"first_name":"Samson","last_name":null}

export default function RootLayout({ children }) {
  const [user, setUser] = useState(null);
  const auth = (e) => {
    if (e === null){
      localStorage.removeItem("iCUBEUser")
    }
    else{
      localStorage.setItem("iCUBEUser", JSON.stringify(e))
    }
    setUser(e)
  }

  useEffect(() => {
    const storedUser = localStorage.getItem('iCUBEUser');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
  }, []);

  return (
    <html lang="en">
      <body>
      <UserContext.Provider value={{user, auth}}>
        <ToastContainer />
        <Navigation user ={user} auth={auth}/>
        <main>{children}</main>
        <Footer/>
        </UserContext.Provider>

      </body>
    </html>
  );
}