"use client"
import { createContext, useState, useEffect } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navigation from './components/Navigation';
import Footer from './components/Footer';
import { GoogleOAuthProvider } from '@react-oauth/google';
import './globals.css'

export const UserContext = createContext(null);

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };


export default function RootLayout({ children }) {
  const [user, setUser] = useState(null);
  const auth = (e) => {
    if (e === null){
      localStorage.removeItem("iCUBEUser")
    }
    else{
      localStorage.setItem("iCUBEUser", JSON.stringify(e))
    }
    setUser(e)
  }
  useEffect(() => {
    const storedUser = localStorage.getItem('iCUBEUser');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
  }, []);

  return (
    <html lang="en">
      <body>
      <UserContext.Provider value={{user, auth}}>
        <GoogleOAuthProvider clientId="575974468902-scorafflscd64ck5mcpekf2ei13elmio.apps.googleusercontent.com">
          <ToastContainer />
          <Navigation user ={user} auth={auth}/>
          <main>{children}</main>
          <Footer/>
        </GoogleOAuthProvider>
        </UserContext.Provider>

      </body>
    </html>
  );
}